### ISSUE TITLE
Not working: "No such a file or directory" error.

### ISSUE THREAD

**Issue by politicus** [lazywei/alfred-omnidict#1]
Great idea! 

From Alfred's debug console:

Starting debug for 'Productivity OmniDict'

[ERROR: alfred.workflow.input.scriptfilter] Code 127: /bin/bash: /Users/lazywei/.pyenv/shims/python: No such file or directory

Is python 3 required? I am using python 2.7.10.

**Comment by lazywei** [comment]
Hi, sorry for not making it general.
A quick solution is go to "Alfred Preference" > "Workflows" > "OmniDict" > double click the "od" Script Filter: 
![image](https://cloud.githubusercontent.com/assets/2840571/11742785/7aa74c22-a03d-11e5-9a76-2b84b440ab4c.png)
and then replace the path to your python interpreter:
![image](https://cloud.githubusercontent.com/assets/2840571/11742796/88b180da-a03d-11e5-9a9f-310723da62f6.png)

As for python's version, I'm afraid Python 3 is required.

Thanks.

**Comment by politicus** [comment]
Thanks for your answer. 

So here is what I tried. 

Using Mac built-in python 2.7 version didn't work. 

Upgraded to version 3. Apparently the interpreter hasn't been installed where is was supposed to be. 

Once I found the interpreter, I changed the script filter of the workflow to this: 

/Library/Frameworks/Python.framework/Versions/3.5/python main.py {query}

I got this error:

[ERROR: alfred.workflow.input.scriptfilter] Code 126: /bin/bash: /Library/Frameworks/Python.framework/Versions/3.5/python: cannot execute binary file

**Comment by lazywei** [comment]
Hi,

A recommended way to install python on Mac OS is using pyenv.
Please check it out here: https://github.com/yyuu/pyenv#homebrew-on-mac-os-x
With pyenv, it will be much easier to locate / switch different version of
python interpreter.

Thanks.

Francois Albert Gandon notifications@github.com 於 2015年12月11日 週五 下午7:59寫道：

**Comment by politicus** [comment]
Ok. 

I successfully installed python 3.5 via pyenv and modified the path of the interpreter accordingly. 

I got the following error in Alfred's console:

[ERROR: alfred.workflow.input.scriptfilter] Code 1: Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

Is there a recommended way to install bs4?

**Comment by lazywei** [comment]
bs4 is refered to beautifulsoup4. Please install it through pip.
You might also need to install 'requests' as well. (via pip too)
Thanks
Francois Albert Gandon notifications@github.com於 2015年12月15日 週二，下午8:54寫道：

**Comment by politicus** [comment]
Ok. Great. 

I had pip installed already. "pip ---version" returned "/Library/Python/2.7/site-packages (python 2.7)"

I am wondering if pip will work with python version 3.5 I installed with pyenv? Do I have to install pip again to make it work with python 3.5?

**Comment by lazywei** [comment]
Please make sure your `pip` refers to `~/.pyenv/shims/pip`. (Through the command `which pip`)
If not, please make sure you setup your $PATH correctly.

Thanks.

**Comment by wonderffee** [comment]
The same problem to politicus. I think it's not a good idea to use absolute path.
At last I solved it, here is my solution(My python3 version is 3.4.1):
1. go to "Alfred Preference" > "Workflows" > "OmniDict" > double click the "od" Script Filter, and then replace the path to:
~/.pyenv/versions/3.4.1/bin/python3 main.py {query}
2. install requests and bs4 for python 3
~/.pyenv/versions/3.4.1/bin/python3  -m pip install requests
~/.pyenv/versions/3.4.1/bin/python3  -m pip install bs4

**Comment by lazywei** [comment]
Thanks @wonderffee. I updated the script according to your suggestion :+1:
